apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: godemo1
  name: godemo1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: godemo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: godemo1
    spec:
      containers:
      - image: yashrv1729/public:2
        name: godemo1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: godemo1
